# Generated by Django 5.2.4 on 2025-10-31 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="doctor_type",
            field=models.CharField(
                choices=[
                    ("vet", "Veterinarian"),
                    ("surgeon", "Surgeon"),
                    ("assistant", "Assistant"),
                ],
                default="vet",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="treatment_type",
            field=models.CharField(
                choices=[
                    ("surgery", "Surgery"),
                    ("checkup", "Checkup"),
                    ("vaccination", "Vaccination"),
                ],
                default="checkup",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="pet",
            name="species",
            field=models.CharField(
                choices=[("dog", "Dog"), ("cat", "Cat"), ("hen", "Hen")],
                default="dog",
                max_length=50,
            ),
        ),
    ]
