# Generated by Django 5.2.4 on 2025-11-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0002_appointment_status_doctor_doctor_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="doctor_images/"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
