# Generated by Django 5.2.4 on 2025-11-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0003_doctor_created_at_doctor_image_doctor_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="is_available",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
