# Generated by Django 5.2.4 on 2025-11-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0006_appointment_availability_appointment_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
