# Generated by Django 5.2.4 on 2025-11-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0007_alter_doctor_is_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="treatment",
        ),
        migrations.AddField(
            model_name="pet",
            name="condition",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="pet_images/"),
        ),
        migrations.DeleteModel(
            name="Treatment",
        ),
    ]
