# Generated by Django 5.2.4 on 2025-11-02 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointment",
            "0008_remove_appointment_treatment_pet_condition_pet_image_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctoravailability",
            name="date",
        ),
        migrations.AddField(
            model_name="doctoravailability",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="doctoravailability",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
