# Generated by Django 5.2.4 on 2025-11-02 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0009_remove_doctoravailability_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctoravailability",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="doctoravailability",
            name="start_date",
        ),
        migrations.AddField(
            model_name="doctoravailability",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
