# Generated by Django 5.2.4 on 2025-07-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(upload_to='img/')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(blank=True, choices=[('Electronics', 'ELECTRONICS'), ('Accessories', 'ACCESSORIES'), ('Clothings', 'CLOTHINGS'), ('Vaccines', 'VACCINES'), ('Petfood', 'PETFOOD')], max_length=15, null=True)),
            ],
        ),
    ]
