# Generated by Django 5.2.4 on 2025-08-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_alter_product_image_alter_product_slug_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Product',
            new_name='product',
        ),
    ]
