# Generated by Django 5.2.4 on 2025-09-08 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ref',
        ),
        migrations.AddField(
            model_name='transaction',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Dog', 'Dogs'), ('Electronics', 'ELECTRONICS'), ('Accessories', 'ACCESSORIES'), ('Clothings', 'CLOTHINGS'), ('Vaccines', 'VACCINES'), ('Petfood', 'PETFOOD')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.cart'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
