# Generated by Django 5.2.4 on 2025-11-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0008_alter_transaction_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="ref",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
