# Generated by Django 5.2.4 on 2025-11-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0009_alter_transaction_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="ref",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
